name: Pull Request Action
on: [pull_request]
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run checks
        run: npx tsc -p tsconfig.json --noEmit
      - run: npx eslint --cache --fix
      - run: npx prettier --check ./src
      - run: echo "🍏 Done"
